### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by okj203** [yungcai/VacationsAway#2]
- [ ] User profile shouldn’t be a table
- [ ] How is stays entity different from reservation entity, is stays entity actually a spots entity? 
- [ ] Consider creating a reviews table and make a rating part of a review
- [ ] One of the tables needs address data (longitude and latitude) for Google Maps API, rather than just a location column.
- [ ] The frontend routes page in wiki needs more info. Please refer to [this link to a sample frontend routes page.](https://github.com/appacademy/2021-04-19-NYC-Lecture-Notes/wiki/Front-End-Routes-&-Components)

**Comment by yungcai** [comment]
Ahh ok , so user profile is just a view we render, we dont need any backend info to fetch?

Stays is basically a listing that is available to be reserved while a reservation is a confirmed stay at specific time? Should I reword it?

So ratings is a bonus on top of the reviews table?

Ok, I will add the frontend and updated map stuff tonight, sorry Ive been too anxious for the assessment to put my mind on this fully :(
